{
 "title": "Account assets",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "account_name",
    "query": "SELECT DISTINCT account_name FROM spot_balances"
   }
  ]
 },
 "panels": [
  {
   "title": "$account_name spot assets",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT asset, total, total_usd, timestamp\nFROM (\n  SELECT account_name, asset, total, total_usd, timestamp,\n    ROW_NUMBER() OVER (PARTITION BY account_name, asset ORDER BY timestamp DESC) AS row_num\n  FROM spot_balances\n  WHERE account_name = '$account_name'\n) AS latest_balances\nWHERE row_num = 1 AND total != 0\nORDER BY asset;"
    }
   ]
  },
  {
   "title": "$account_name futures assets",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT asset, total, total_usd, timestamp\nFROM (\n  SELECT account_name, asset, total, total_usd, timestamp,\n    ROW_NUMBER() OVER (PARTITION BY account_name, asset ORDER BY timestamp DESC) AS row_num\n  FROM futures_balances\n  WHERE account_name = '$account_name'\n) AS latest_balances\nWHERE row_num = 1 AND total != 0\nORDER BY asset;"
    }
   ]
  },
  {
   "title": "$account_name futures positions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH current_prices AS (\n  SELECT \n    exchange, account_type, instrument, (bid + ask)/2 as price\n  FROM price_tickers\n  WHERE exchange = 'BINANCE' and account_type = 'LINEAR_FUTURES'\n  LATEST ON timestamp PARTITION BY instrument\n)\nSELECT pos.instrument, account_name, pos.account_type, position_side, amount, price_entry, price, unrealized_profit\nFROM positions pos\nINNER JOIN current_prices ON (instrument)\nWHERE pos.exchange = 'BINANCE' and pos.account_type = 'LINEAR_FUTURES' and pos.account_name = '$account_name'\nLATEST ON timestamp PARTITION BY instrument;"
    }
   ]
  }
 ]
}