{
 "title": "Tables data updates",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "public_data_table",
    "label": "Public data tables",
    "query": "trades, orderbook, price_tickers"
   }
  ]
 },
 "panels": [
  {
   "title": "$public_data_table updates",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT instrument, timestamp FROM $public_data_table LATEST ON timestamp PARTITION BY instrument ORDER BY timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Spot balances",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT account_name, timestamp FROM spot_balances LATEST ON timestamp PARTITION BY account_name ORDER BY timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Future balances",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT account_name, timestamp FROM futures_balances LATEST ON timestamp PARTITION BY account_name ORDER BY timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT account_name, account_type, timestamp FROM orders LATEST ON timestamp PARTITION BY account_name, account_type ORDER BY timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Positions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT account_name, timestamp FROM positions LATEST ON timestamp PARTITION BY account_name ORDER BY timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Private trades",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT account_name, account_type, timestamp FROM et_trades LATEST ON timestamp PARTITION BY account_name, account_type ORDER BY timestamp DESC;\n"
    }
   ]
  }
 ]
}